=== NSkam/xml-test/schedule_4.xsd
<?xml version="1.0"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                      targetNamespace="schedule"
                      xmlns="schedule"
                      elementFormDefault="qualified">
    <xsd:element name="Schedule">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Event"  maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Title" type="xsd:string"/>
							<!--START OF CHANGES-->
                            <xsd:element name="Lecture" minOccurs="1" maxOccurs="10">
							<!--END OF CHANGES-->
							    <xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Day">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:pattern value="Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Time">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:pattern value="[0-9][0-9]:[0-9][0-9]-[0-9][0-9]:[0-9][0-9]"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== NSkam/xml-test/4_RIGHT_schedule.xml
<?xml version="1.0"?> 
<Schedule xmlns ="schedule"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="schedule_4.xsd">
        <Event>
                <Title>Artificial Intelligence</Title>
                <Lecture>
					<Day>Wednesday</Day>
					<Time>09:00-11:30</Time>
				</Lecture>
				<Lecture>
					<Day>Thursday</Day>
					<Time>12:00-13:30</Time>
				</Lecture>
        </Event>
		<Event>
                <Title>Knowledge Representation in Web</Title>
                <Lecture>
					<Day>Friday</Day>
					<Time>15:30-17:00</Time>
				</Lecture>
        </Event>
</Schedule>
